config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :spots do
    resources :bookings, only: [:create, :new, :show, :index] do
      resources :messages, only: [:new, :create]
    end
  end
  resources :reviews

  resources :bookings, only: [:show, :edit, :update, :destroy]


  # get 'user/edit_profile', to: "users#edit"


  #patch '/user/update', to: 'users#update', as: :user
  get '/index', to: 'pages#index'
  get '/profile', to: 'users#profile', as: :profile

  # get '/spot/new', to: 'spots#new', as: :new_spot
  # post '/spot/create', to: 'spots#create', as: :create_spot
  # patch '/spot/:id/update', to: 'spots#update', as: :update_spot
  # get '/spot/:id', to: 'spots#show', as: :spots
  # get '/user/:id', to: 'users#show', as: :spot_user

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :spot
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :sender, class_name: "User"
  belongs_to :receiver, class_name: "User"
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user

  validates :content, length: { minimum: 20 }
end

app/models/spot.rb
class Spot < ApplicationRecord
  belongs_to :user
  mount_uploader :photo, PhotoUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  mount_uploader :photo, PhotoUploader
  has_many :sent_messages, foreign_key: :sender_id, class_name: "Message"
  has_many :received_messages, foreign_key: :receiver_id, class_name: "Message"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  helper_method :get_base_url
  def get_base_url
    @base_url2 = "https://s3.eu-west-3.amazonaws.com/lasthome/uploads"
  end

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def index

    @user = current_user
    @bookings = Booking.where("user_id=?", @user.id)
  end

  def create
    @spot = Spot.find(params[:spot_id])
    bkg = Booking.new(user: current_user, spot: @spot)
    if bkg.save
      redirect_to spot_booking_path(@spot, bkg)
    else
      redirect_to spot_path(@spot)
    end
  end

  def show
    @base_url = "https://s3.eu-west-3.amazonaws.com/lasthome/uploads"
    @booking = Booking.find(params[:id])
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to spot_bookings_path(@booking.spot_id)
  end

  private

  def booking_params
    params.require(:spot).permit(:user, :id)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def new
    @msg = Message.new
  end

  def create
  end

  private

  def msg_params

  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    @base_url = "https://s3.eu-west-3.amazonaws.com/lasthome/uploads/"
    @spots = Spot.all
  end

  def index
    @base_url = "https://s3.eu-west-3.amazonaws.com/lasthome/uploads/"
    p params[:search_content]
    p params[:search_content].present?
    p params[:good_or_evil]
    p params[:good_or_evil].present?
    good_or_evil = params[:good_or_evil] == "Good"
    if params[:search_content].present? && params[:good_or_evil].present?
      p "cas 1"
      @spots = Spot.where("occupation ILIKE '%#{params[:search_content]}%' AND good=?", good_or_evil)
    elsif params[:search_content].present?
      p "cas 2"
      @spots = Spot.where("occupation ILIKE '%#{params[:search_content]}%'")
    elsif params[:good_or_evil].present?
      p "cas 3"
      @spots = Spot.where("good=?", good_or_evil)
    else
      p "cas 4"
      @spots = Spot.all
    end
    p @spots
    @spots = Spot.all if @spots == []
    p @spots
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    # POST /restaurants/:restaurant_id/reviews
  def create
    @review = Review.new(review_params)
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review.restaurant = @restaurant
    @new_review = Review.new

    respond_to do |format|
      if @review.save
        format.html { redirect_to restaurant_path(@restaurant) }
        format.js { }
      else
        format.html { render 'restaurants/show' }
        format.js { }
      end
    end
  end

  private

  def review_params
    params.require(:review).permit(:content)
  end
end

app/controllers/spots_controller.rb
class SpotsController < ApplicationController

  def index
  end

  def new
    @spot = Spot.new
    @spot.user = current_user
    @user = @spot.user
  end

  def create
    new_params = spot_params
    p new_params
    new_params[:image] = spot_params[:photo]
    p new_params[:image]
    @spot = Spot.new(new_params)
    p @spot
    @spot.user = current_user
    p @spot
    if @spot.save
      redirect_to spot_path(@spot)
    else
      render :new
    end
  end

  def show
    @base_url = "https://s3.eu-west-3.amazonaws.com/lasthome/uploads/"
    @spot = Spot.find(params[:id])
    @booking = Booking.new
  end

  def destroy
    @spot = Spot.find(params[:id])
    @spot.destroy
  end

  private

  def spot_params
    params.require(:spot).permit(:description, :price, :guest_number, :image, :occupation, :good, :photo)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def edit
    @user = current_user
  end

  def profile
    @user = current_user
    @spot = Spot.where("user_id=?", current_user.id)
    if @spot != []
      @booking = find_booking_from_owner(@spot)
    else
      @booking = Booking.where("user_id=?", current_user.id)
      @spot = @booking.spot_id
    end
  end


  def find_booking_from_owner
    @booking = Booking.where("spot_id=?", @spot.id)
  end

  def update
    current_user.name = user_params[:name]
    current_user.avatar = user_params[:photo]
    if current_user.save
      redirect_to root_path
    else
      render :edit
    end
  end

  def show
    @base_url = "https://s3.eu-west-3.amazonaws.com/lasthome/uploads/"
    @user = User.find(params[:id])
  end


  private

  def user_params
    params.require(:user).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<%
 if params['good_or_evil'] == "Good"
   background_path = "#{@base_url}good.jpg"
 else
   background_path = "#{@base_url}evil.jpg"
 end
%>
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('<%= background_path %>');">
  <% @bookings.each do |booking| %>
    <img src=<%= booking.spot.photo.url %>>
    <h3 class="yourbookingtitle">Your booking</h3>
    <div>
      <img class="avatarbooking"  src=<%= booking.spot.user.photo.url %> >
    </div>
      <div class="usernamebook">
        <h4> Hello <strong><%= booking.user.name %></strong>, pleased to introduce you to your last friend,<strong> <%= booking.spot.user.name %></strong>.<br> Hope you will spend good time together for the eternity..</h4>
      </div>
      <div class="spotdescr">
        <%= booking.spot.description %>
      </div>
      <div class="deletespot">
      <p> Don't want to stay anymore with <strong> <%= booking.spot.user.name %></strong> ?, click here : <%= link_to '<i class="fas fa-trash-alt"></i>'.html_safe, booking_path(booking), method: :delete %></p>
      </div>
    <% end %>
</div>

app/views/bookings/show.html.erb
<h3>Your Spot</h3>
<body>
    <div class="container">
      <div class="profile text-center">
        <div class="main">
          <div class="main-content">
            <img class="avatar" src=<%= @booking.spot.user.photo.url %>>
            <h2><%= @booking.spot.user.name %></h2>
            <hr>
            <%= link_to "Back to spots", index_path, method: :get %>
          </div>
        </div>
        <div class="stat">
          <div class="stat-content">
            <h3>Price</h3>
            <p><%= @booking.spot.price %></p>
          </div>
        </div>
        <div class="stat">
          <div class="stat-content">
            <h3>Occupation</h3>
            <p><%= @booking.spot.occupation %></p>
          </div>
          </div>
        <div class="stat">
          <div class="stat-content">
            <h3>Description</h3>
            <p><%= @booking.spot.description %></p>
          </div>
          </div>
        <div class="description" >
          <img class="image_fond" src=<%= @booking.spot.photo.url %>>
        </div>
      </div>
    </div>
</body>

<%= link_to "Back to spots", index_path %>

app/views/layouts/_navbar.html.erb
<% logo = ENV['BASE_URL'] + "logo.png" %>
<% source = user_signed_in? ? current_user.photo.url : logo %>
<div class="navbar-wagon-right ">
  <div class= "navbar-wagon-brand">
    <%= link_to image_tag("logo.png"), root_path   %>
  </div>

  <div class="navbar-wagon">
<!-- Right Navigation -->
    <div class= "navbar-wagon-brand">
      <%= link_to 'Add spot', new_spot_path if user_signed_in? %>
      <%= link_to "See your booking", spot_bookings_path(:spot, :booking) if user_signed_in? %>
    </div>

  <!-- Profile picture with dropdown list -->
    <div class="navbar-wagon-item">
      <div class="dropdown">

        <!-- <div class="avatar dropdown-toggle" id="navbar-wagon-menu" data-toggle="dropdown"> -->
        <img class="avatar dropdown-toggle" id="navbar-wagon-menu" data-toggle="dropdown" src=<%= source %>> <!-- mettre ici le code erb pour la photo de profile -->
        <!-- </div> -->
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><%= link_to "log in", new_user_session_path %></li>
          <li><%= link_to "log out", destroy_user_session_path, method: :delete%></li>
          <li><%= link_to 'Update profile', edit_user_registration_path   if user_signed_in? %>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Last Home</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'layouts/navbar' %>
    <p class="alert"><%= alert %></p>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/messages/new.html.erb
<%= simple_form_for [@booking, @spot, @msg] do |f| %>
To: <%= @spot.user_id.name %>
From: <%= @booking.user_id.name %>
<%= f.input :content %>
<%= f.submit :send_message %>
<% end %>

app/views/pages/home.html.erb
<div class="banner" style="background-image: url('<%= "#{@base_url}banner.jpg" %>')">

  <div class="banner-content">
    <h1>Last home</h1>
    <p class="home-title">A spot for eternity</p>
      <div class="card-home">
        <h2 class="fylh"> Find your last home: </h2>
        <p class="fylhp"> Chose your neighbour for the eternity</p>
       <form action='/index' method='get'>

        <input type="text" name='search_content' placeholder='Occupation' class="contentsearch">
        <select class="goodev" id="good_evil" name="good_or_evil">
          <option value="Good">Good</option>
          <option value="Evil">Evil</option>
        </select>
        <br>
        <br>
        <input type="submit" value="Search" class="btn btn-primary btnsearch">
        </form>
        <br>
        <br>
        <br>
    </div>
</div>
</body>

app/views/pages/index.html.erb
<%
  if params['good_or_evil'] == "Good"
    background_path = "#{@base_url}good.jpg"
    content_good = "WELCOME TO PARADISE"
    content_text = "There is a place for everyone"
  else
    background_path = "#{@base_url}evil.jpg"
    content_good = "WELCOME TO HELL"
    content_text = "Hurry up there will not be enough room"
  end
%>


<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('<%= background_path %>');">
  <div class="banner-content">
    <% if params['good_or_evil'] == "Good" %>
    <h1><%= "#{content_good}" %></h1>
    <p><%= "#{content_text}" %></p>
    <% else %>
    <h1><%= "#{content_good}" %></h1>
    <p><%= "#{content_text}" %></p>
    <% end  %>
  </div>
</div>

<div class="container">
  <div class="row">
    <% @spots.each do |spot| %>
      <div class="col-md-4">
        <div class="card-spot" style= "background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(<%= spot.photo.url %>)">
          <div class="card-category"><%= spot.user.name %></div>
          <div class="card-description">
            <h2>Occupation : <%= spot.occupation %></h2>
            <p>Price : <%= spot.price %></p>
          </div>
          <img class="card-user" src=<%= spot.user.photo.url %> alt="Image">
          <%= link_to "toto", spot_path(spot), class: "card-link" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/reviews/_form.html.erb
<%= simple_form_for([spot, review], remote: true) do |f| %>
  <%= f.input :content %>
  <%= f.submit %>
<% end %>

app/views/reviews/_show.html.erb
<p><%= review.content %></p>

app/views/reviews/create.js.erb
function refreshForm(innerHTML) {
  const newReviewForm = document.getElementById('new_review');
  newReviewForm.innerHTML = innerHTML;
}

function addReview(reviewHTML) {
  const reviews = document.getElementById('reviews');
  reviews.insertAdjacentHTML('beforeend', reviewHTML);
}

<% if @review.errors.present? %>
  refreshForm('<%= j render "reviews/form", spot: @spot, review: @review %>');
<% else %>
  addReview('<%= j render "reviews/show", review: @review %>');
  refreshForm('<%= j render "reviews/form", spot: @spot, review: @new_review.new %>');
<% end %>

app/views/spots/index.html.erb
<h1>Reviews</h1>

<ul>
  <% @reviews.each do |review| %>
    <li data-id="<%= review.id %>">
      <%= link_to review.name, review_path(review) %>
      <%= link_to "Delete", review_path(review), method: :delete, remote: true %>
    </li>
  <% end %>
</ul>

app/views/spots/new.html.erb
<div class="form">
  <%= simple_form_for @spot do |f| %>
  <%= f.input :description %>
  <%= f.input :guest_number %>
  <%= f.input :price %>
  <%= f.input :photo %>
  <%= f.input :good, collection: ['Good', 'Evil'] %>
  <%= f.input :occupation %>
  <%= f.submit :create_spot %>
  <% end %>
</div>

app/views/spots/show.html.erb
  <div class="showcard" style= "background-image: url(<%= @spot.photo.url %>)">

    <div><img src=<%= @spot.user.photo.url %> class="spotavatar"></div>

      <div class="spotname"><%= @spot.user.name %></div>
      <br>
      <div class="spotoccupation"><h2><%= @spot.occupation %></h2></div>
      <br>
    <div class="card menu">
      <ul>
        <lo><div class="spotdescription"><h2>"<%= @spot.description %>"</h2></div></lo>
   <!--    <div class="spotgood"><%= @spot.good %></div> -->
      <lo><div class="gestnum"><p> Available places :<%= @spot.guest_number %></p><lo></div>
      <lo><div class="price"><h3>Special price $ : <%= @spot.price %></h3></div></lo>
      <br>
      <lo><%= simple_form_for [@spot, @booking] do |f| %>
        <%= f.submit class: 'btn btn-primary book' %>
      <% end %></lo>
    </ul>
    </div>
  </div>

app/views/users/edit.html.erb
<%= simple_form_for(@user) do |f| %>
<%= f.input :name %>
<%= f.input :photo %>
<%= f.submit :update %>
<% end %>

app/views/users/profile.html.erb
<img src=<%= @user.photo.url %>>
<%= @user.name %>
<%= @user.email %>
<%= link_to "Send message", new_spot_booking_message(@spot, @booking) %>